apiVersion: backstage.io/v1alpha1
kind: Resource
identifier: testbackstage
metadata:
  name: artists-db
  description: Stores artist details
spec:
  type: database
  owner: team-a
  system: artist-engagement-portal
