apiVersion: harness.io/v1
kind: Workflow
type: harness_project
identifier: test_workflow_remote
name: Test Workflow  Remote
owner: user:account/samriddhi.daga+rbac@harness.io
orgIdentifier: default
projectIdentifier: DeepeshIDP
spec:
  output:
    links:
    - title: Pipeline Details
      url: ${{ steps.trigger.output.PipelineUrl }}
    text:
    - title: Outputs
      apiKeySecret: DeepeshHarnessPAT
      content: "url: ${{ steps.provision_workspace.output.PipelineUrl }}\nOutput Variable\
        \ o is: ${{ steps.provision_workspace.output['pipeline.stages.ci.spec.execution.steps.Run_1.output.outputVariables.some_stat']\
        \ }} "
  lifecycle: production
  parameters:
  - title: User Onboarding Details
    required:
    - username
    - organization_id
    - project_id
    - user_group_id
    properties:
      token:
        title: Harness Token
        type: string
        ui:widget: password
        ui:field: HarnessAuthToken
      service_name:
        title: Service Name
        type: string
        description: Mention the project name
      username:
        title: Username
        type: array
        description: Select an existing user to grant access
        ui:field: MultiEntityPicker
        ui:options:
          allowArbitraryValues: false
          catalogFilter:
          - kind: User
      organization_id:
        title: Harness organization
        type: string
        description: Select your existing Harness organization
        pattern: ^([a-zA-Z][_a-zA-Z0-9]*)$
        ui:field: HarnessOrgPicker
        ui:autofocus: true
      project_id:
        type: string
        ui:field: SelectFieldFromApi
        dependsOn: organization_id
        ui:options:
          title: Harness Project
          placeholder: Select your Harness Project identifier
          allowArbitraryValues: false
          path: proxy/harness-api/v1/orgs/{{ parameters.organization_id }}/projects
          valueSelector: project.identifier
          labelSelector: project.name
      user_group_id:
        type: string
        ui:field: SelectFieldFromApi
        dependsOn: project_id
        ui:options:
          title: User group
          placeholder: Select the user group to assign
          allowArbitraryValues: false
          path: proxy/harness-api/ng/api/user-groups?accountIdentifier=rzjR8UyZTpOAd6SLDfdBuw&orgIdentifier={{parameters.organization_id}}&projectIdentifier={{parameters.project_id}}&filterType=INCLUDE_INHERITED_GROUPS
          arraySelector: data.content
          valueSelector: identifier
          labelSelector: name
  steps:
  - id: provision_workspace
    name: Onboarding user
    action: trigger:harness-custom-pipeline
    input:
      url: https://qa.harness.io/ng/account/rzjR8UyZTpOAd6SLDfdBuw/all/cd/orgs/default/projects/DeepeshIDP/pipelines/User_Onboarding/pipeline-studio
      inputset:
        service_name: ${{ parameters.service_name }}
        USERNAME: ${{ parameters.username }}
        ORGANIZATION_ID: ${{ parameters.organization_id }}
        PROJECT_ID: ${{ parameters.project_id }}
        USER_GROUP_ID: ${{ parameters.user_group_id }}
      apikey: ${{ parameters.token }}
      apiKeySecret: DeepeshHarnessPAT
      showOutputVariables: true
  ownedBy:
  - user:account/samriddhi.daga+rbac@harness.io
metadata:
  annotations:
    backstage.io/source-location: url:https://app.harness.io/ng/account/WqS38aeyQjayoqy6mzwceA/all/code/orgs/default/projects/idpgenerated/repos/idp/files/main/~/harness-workflows/
  tags:
  - java
  - java.t
