apiVersion: harness.io/v1
kind: Component
type: service
identifier: test_sync_entity
name: Test sync entity
owner: user:account/samriddhi.daga@harness.io
spec:
  lifecycle: production
metadata:
  tags:
  - bn
  - spotify
