apiVersion: harness.io/v1
kind: Component
type: component
identifier: test_gitx_for_temp_project
name: Test Gitx for Temp project
owner: user:account/admin@harness.io
orgIdentifier: Demo
projectIdentifier: projectdemo
spec:
  lifecycle: production
  ownedBy:
  - user:account/admin@harness.io
metadata:
  tags:
  - rest
  - users
