apiVersion: harness.io/v1
kind: Component
type: service
identifier: testgitxforbranchtemp
name: Test Backstage Component
owner: user:account/admin@harness.io
spec:
  lifecycle: production
  ownedBy:
  - user:account/admin@harness.io
