apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testgitxforbranchtemp
  title: Test gitx for branch temp Backstage
  tags:
    - mqtt
    - authentication
  annotations:
    backstage.io/managed-by-location: url:https://github.com/samriddhi-daga/idp-template/new/temp-branch
    backstage.io/managed-by-origin-location: url:https://github.com/samriddhi-daga/idp-template/new/temp-branch
spec:
  type: website
  lifecycle: production
  owner: user:admin@harness.io
