apiVersion: harness.io/v1
kind: Component
type: service
identifier: test_gitx_for_component
name: Test Gitx for Component
owner: user:account/admin@harness.io
spec:
  lifecycle: experimental
  ownedBy:
  - user:account/admin@harness.io
