apiVersion: harness.io/v1
kind: Component
type: component
identifier: test_gitx_component_update
name: Test Gitx Component Update
owner: user:account/admin@harness.io
spec:
  lifecycle: experimental
  ownedBy:
  - user:account/admin@harness.io
