apiVersion: harness.io/v1
kind: Component
type: service
identifier: test_project_webhook_event
name: Test Project Webhook Event
owner: user:account/samriddhi.daga+rbac@harness.io
orgIdentifier: default
projectIdentifier: idptest
spec:
  lifecycle: production
  ownedBy:
  - group:account/_account_all_users
  - user:account/samriddhi.daga+rbac@harness.io
metadata:
  tags:
  - java
  - my-sample-github
