apiVersion: harness.io/v1
kind: Workflow
type: service
identifier: triggergroupedpipeline
name: Dual Pipeline Workflow with Group
owner: user:account/samriddhi.daga@harness.io
spec:
  parameters:
  - title: Service Information
    required:
    - token
    properties:
      service_name:
        title: Service Name
        type: string
        description: Name of the service
      environment:
        title: Environment
        type: string
        description: Target environment for deployment
      description:
        title: Description
        type: string
        description: Description of the service
        ui:widget: textarea
      token:
        title: Harness Token
        type: string
        description: Authentication token for Harness API
        ui:widget: password
        ui:field: HarnessAuthToken
  steps:
  - id: fetch-repo
    name: Fetch Source Code
    action: fetch:plain
    input:
      url: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/resources/artists-db-resource.yaml
      targetPath: ./fetched-config
  - id: test_pipeline
    name: Grouped Pipeline
    action: trigger:harness-custom-pipeline
    input:
      url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/all/orgs/default/projects/IDPtest/pipelines/Samriddhi_Test_2/pipeline-studio/?storeType=INLINE
      inputset: {}
      apikey: ${{ parameters.token }}
    onFailure:
      action: abort
      errors:
      - Pipeline execution failed
metadata:
  description: A workflow that triggers two Harness pipelines in sequence
  tags:
  - test
  - pipeline
  - workflow
