apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-setup
  template:
    metadata:
      labels:
        app: local-setup
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: local-setup
spec:
  selector:
    app: local-setup
  ports:
    - port: 80
      targetPort: 80
